### ISSUE TITLE
Stats are invisible in the end

### ISSUE THREAD

**Issue by bretonium** [ResamVi/infclass-stats#18]
Only several lines are visible for me in DDNet client.

![screenshot_20190120_192604](https://user-images.githubusercontent.com/1087672/51443499-e8c9ae80-1ce9-11e9-9bb9-f2fa64be6013.jpeg)

**Comment by ResamVi** [comment]
yavl discussed this:
DDNnet has "Show Chat"
![grafik](https://user-images.githubusercontent.com/6261556/51677560-591e4b80-1fda-11e9-8642-2d0eea159b92.png)
to get a bigger history of the view.

I question whether or not to keep "best class" section at all because I don't think anybody cares enough about a specific class

**Comment by bretonium** [comment]
And this button does not work in the end of the map, at least for me

**Comment by ResamVi** [comment]
7 lines can be displayed while scoreboard is open

best players in each class deleted 50a21b5f4845a452940c364b83ea30862c019d24
